name = "TableFormatter"
uuid = "3da99bb1-9270-4ae4-a7cd-1ed676c4bb49"
authors = ["Antonino DAnna <antonino.danna@estudiante.uam.es>"]
version = "1.2.0"

[deps]
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"

